<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">

            <a class="navbar-brand" href="/"><p style="max-height:100%;">✅  <b>HOST</b> WEB </p></a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">

            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="/index/logout">Sair</a>
                </li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
