<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"
    <meta name="author" content="Jean Chagas">


   <!-- <link href="<?php echo _DOMAIN . DS . ASSETS; ?>/img/favicon.ico" rel="shortcut icon"> -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700" rel="stylesheet" type="text/css"/>
    <link href="<?php echo _DOMAIN . DS . ASSETS; ?>/css/jquery-ui.css" rel="stylesheet" type="text/css"/>
    <link href="<?php echo _DOMAIN . DS . ASSETS; ?>/css/custom.styles.min.css" rel="stylesheet" type="text/css"/>
    <link href="<?php echo _DOMAIN . DS . ASSETS; ?>/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>

    <title><?php echo $this->title(); ?> page - TCC ADS</title>


</head>
